# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/zecoxao/Desktop/ps5-pup-unpacker

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/zecoxao/Desktop/ps5-pup-unpacker

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/zecoxao/Desktop/ps5-pup-unpacker/CMakeFiles /mnt/c/Users/zecoxao/Desktop/ps5-pup-unpacker//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/zecoxao/Desktop/ps5-pup-unpacker/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pup_unpacker

# Build rule for target.
pup_unpacker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pup_unpacker
.PHONY : pup_unpacker

# fast build rule for target.
pup_unpacker/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pup_unpacker.dir/build.make CMakeFiles/pup_unpacker.dir/build
.PHONY : pup_unpacker/fast

#=============================================================================
# Target rules for targets named zlibstatic

# Build rule for target.
zlibstatic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlibstatic
.PHONY : zlibstatic

# fast build rule for target.
zlibstatic/fast:
	$(MAKE) $(MAKESILENT) -f extern/zlib-1.2.8/CMakeFiles/zlibstatic.dir/build.make extern/zlib-1.2.8/CMakeFiles/zlibstatic.dir/build
.PHONY : zlibstatic/fast

MainApp.o: MainApp.cpp.o
.PHONY : MainApp.o

# target to build an object file
MainApp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pup_unpacker.dir/build.make CMakeFiles/pup_unpacker.dir/MainApp.cpp.o
.PHONY : MainApp.cpp.o

MainApp.i: MainApp.cpp.i
.PHONY : MainApp.i

# target to preprocess a source file
MainApp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pup_unpacker.dir/build.make CMakeFiles/pup_unpacker.dir/MainApp.cpp.i
.PHONY : MainApp.cpp.i

MainApp.s: MainApp.cpp.s
.PHONY : MainApp.s

# target to generate assembly for a file
MainApp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pup_unpacker.dir/build.make CMakeFiles/pup_unpacker.dir/MainApp.cpp.s
.PHONY : MainApp.cpp.s

PUP.o: PUP.cpp.o
.PHONY : PUP.o

# target to build an object file
PUP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pup_unpacker.dir/build.make CMakeFiles/pup_unpacker.dir/PUP.cpp.o
.PHONY : PUP.cpp.o

PUP.i: PUP.cpp.i
.PHONY : PUP.i

# target to preprocess a source file
PUP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pup_unpacker.dir/build.make CMakeFiles/pup_unpacker.dir/PUP.cpp.i
.PHONY : PUP.cpp.i

PUP.s: PUP.cpp.s
.PHONY : PUP.s

# target to generate assembly for a file
PUP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pup_unpacker.dir/build.make CMakeFiles/pup_unpacker.dir/PUP.cpp.s
.PHONY : PUP.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pup_unpacker.dir/build.make CMakeFiles/pup_unpacker.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pup_unpacker.dir/build.make CMakeFiles/pup_unpacker.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pup_unpacker.dir/build.make CMakeFiles/pup_unpacker.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pup_unpacker"
	@echo "... zlibstatic"
	@echo "... MainApp.o"
	@echo "... MainApp.i"
	@echo "... MainApp.s"
	@echo "... PUP.o"
	@echo "... PUP.i"
	@echo "... PUP.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

